name: ghcr-login

description: Login to GitHub Container Registry

inputs:
  githubToken:
    description: "GitHub token to login to the GitHub Container Registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Log into GitHub Container Registry
      run: |
        env | sort
        echo "Login as ${{ github.actor }} with passwrod '${{ inputs.githubToken }}'"
      # run: echo "${INPUT_GITHUBTOKEN}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash
