name: ghcr-login

description: Login to GitHub Container Registry

runs:
  using: "composite"
  steps:
    - name: Log into GitHub Container Registry
      # run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash
      run: echo "Login to GCR as ${{ github.actor }}"
