name: Build and publish ansible

on:
  push:
    paths:
      - "ansible/**"
    branches:
      - 'main'

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/ghcr-login
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build-push-image
        with:
          imageName: ansible
