name: Build and publish backup-tools

on:
  push:
    paths:
      - "backup-tools/**"
    branches:
      - 'main'

jobs:
  call-build-and-push-workflow:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      imageName: backup-tools
