name: build-and-push

on:
  workflow_dispatch:
    inputs:
      imageName:
        required: true
        type: string
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        id: get_version
        run: |
          if [ -f ./${{ inputs.imageName }}/version ]
          then
            VERSION=$(cat ./${{ inputs.imageName }}/version)
          else
            VERSION=latest
          fi
          echo "Building version: ${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/rchrd/${{ inputs.imageName }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.get_version.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ inputs.imageName }}
            org.opencontainers.image.version=${{ steps.get_version.outputs.version }}

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.imageName }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
