name: Build and publish kube-tools

on:
  push:
    paths:
      - "kube-tools/**"

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/ghcr-login

      - uses: ./.github/actions/build-push-image
        with:
          imageName: kube-tools
