name: Build and publish kube-tools

on:
  push:
    paths:
      - "kube-tools/**"
    branches:
      - 'main'

jobs:
  call-build-and-push-workflow:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      imageName: kube-tools
