name: Build and publish node-red

on:
  push:
    paths:
      - "node-red/**"
    branches:
      - 'main'
      - 'multi-arch'

jobs:
  call-build-and-push-workflow:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      imageName: node-red
