name: test

on: ["push"]

env:
  IMAGE_NAME: node-red

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          ls -l
          ls -l ./${{ env.IMAGE_NAME }}
          if [ -f ./${{ env.IMAGE_NAME }}/version ]
          then
            VERSION=$(cat ./${{ env.IMAGE_NAME }}/version)
          else
            VERSION=latest
          fi
          echo "${VERSION}"
          echo "::set-output name=version::${VERSION}"

      - run: |
          echo "IMAGE_NAME=${{ env.IMAGE_NAME }}"
          echo "version: ${{steps.get_version.outputs.version}}"
          echo "outputs: ${{steps.get_version.outputs.*}}"

      - name: Docker meta
        id: test_id
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/rchrd/test
          tags: |
            type=raw,value=latest
            type=raw,value=${{steps.get_version.outputs.version}}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
