name: test

on: ["push"]

env:
  IMAGE_NAME: node-red

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: |
          if [ -f ./${{ inputs.imageName }}/version ]
          then
            VERSION=$(cat ./${{ inputs.imageName }}/version)
          else
            VERSION=latest
          fi
          echo "${VERSION}"
          echo "::set-output name=version::${VERSION}"

      - run: |
          echo "IMAGE_NAME=${IMAGE_NAME}"
          echo "version: ${{steps.get_version.outputs.version}}"
          echo "output: ${{steps.get_version.outputs.*}}"

      - name: Docker meta
        id: test_id
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/rchrd/test
          tags: |
            type=raw,value=latest
            type=raw,value=${{steps.get_version.outputs.version}}
          labels: |
            org.opencontainers.image.title=${IMAGE_NAME}
