name: test

on: ["push"]

env:
  IMAGE_NAME: node-red

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          if [ -f ./${{ env.IMAGE_NAME }}/version ]
          then
            VERSION=$(cat ./${{ env.IMAGE_NAME }}/version)
          else
            VERSION=latest
          fi
          echo "${VERSION}"
          echo "::set-output name=version::${VERSION}"

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/rchrd/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.get_version.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.version=${{ steps.get_version.outputs.version }}
